#!/usr/bin/env bash
# Stage 5: encoder comparison on carla_right_turn_simple.
#
# Every arm (cnn, custom_jepa = Phase 2 EMA encoder, vjepa2) trains with the
# same seed(s), step budget, observation (front camera + route vector),
# discrete actions, reward (time penalty 0.1, as in the passed Stage 3 run) and
# train_ratio 512. One queue step per arm and seed; each resumes from its own
# checkpoint if the script is started again. CARLA 0.9.15 occasionally
# segfaults on an episode reset; a failed arm is retried (CARLA restarted,
# training resumed from its checkpoint) up to MAX_ATTEMPTS times, with a
# separate CARLA log per attempt. Finally the finished runs are aggregated
# into <dir>/comparison.md / comparison.json (mean +- std, steps to 80%
# success, route completion, wall clock, VRAM).
#
# Start detached with sleep blocked:
#   mkdir -p outputs/comparison_queue
#   setsid nohup systemd-inhibit --what=sleep:idle:handle-lid-switch --why=training \
#     bash jobs/comparison.sh >> outputs/comparison_queue/run.log 2>&1 &
# Watch:  python3 scripts/watch_queue.py --out outputs/comparison_queue
# Stop:   touch outputs/comparison_queue/STOP
# Do not edit this file while it runs: bash reads scripts incrementally.

set -uo pipefail
PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
PY="$PROJECT_ROOT/.venv/bin/python"
OUT="${OUT:-outputs/comparison_queue}"
export CARLA_ROOT="${CARLA_ROOT:-$HOME/software/CARLA_0.9.15}"
TASK="${TASK:-carla_right_turn_simple}"
STEPS="${STEPS:-100000}"
SEEDS="${SEEDS:-42}"
ARMS="${ARMS:-cnn custom_jepa vjepa2}"
TIME_PENALTY="${TIME_PENALTY:-0.1}"
RUN_DIR="${RUN_DIR:-outputs/comparison/${TASK}_camera_route}"
EXTRA_SET="${EXTRA_SET:-}"   # e.g. "--set prefill=500 --set eval_episode_num=1" for a smoke test
MAX_ATTEMPTS="${MAX_ATTEMPTS:-6}"

source "$PROJECT_ROOT/jobs/lib_queue.sh"

# Step list for scripts/watch_queue.py (estimated hours weight the overall bar).
"$PY" - "$OUT/steps.json" "$RUN_DIR" "$STEPS" "$SEEDS" "$ARMS" <<'PY'
import json, sys
path, run_dir, steps, seeds, arms = sys.argv[1:]
hours = {"cnn": 6.3, "custom_jepa": 5.9, "vjepa2": 7.6}  # measured at train_ratio 512
scale = int(steps) / 100_000
entries = [{"name": f"{arm}_seed{seed}", "logdir": f"{run_dir}/{arm}_seed{seed}",
            "target": int(steps), "hours": hours.get(arm, 6.0) * scale}
           for seed in seeds.split() for arm in arms.split()]
entries.append({"name": "aggregate", "hours": 0.01})
json.dump(entries, open(path, "w"), indent=1)
PY

start_queue "encoder comparison (${ARMS}; seeds ${SEEDS}; ${STEPS} steps)"
for seed in $SEEDS; do
  for arm in $ARMS; do
    logdir="$RUN_DIR/${arm}_seed${seed}"
    if [[ -f "$logdir/metrics.json" ]]; then
      status "DONE  ${arm}_seed${seed} (metrics.json exists)"
      continue
    fi
    name="${arm}_seed${seed}"
    for attempt in $(seq 1 "$MAX_ATTEMPTS"); do
      resume=""
      [[ -f "$logdir/latest.pt" ]] && resume="--resume"
      run_step "$name" env RUN_MODE="$arm" SEED="$seed" OBS=camera_route \
        ACTION=discrete STEPS="$STEPS" CARLA_LOG="$PROJECT_ROOT/$OUT/carla_${name}_try${attempt}.log" \
        TRAIN_ARGS="$resume --logdir $logdir --set train_ratio=512 --env-set reward.scales.time=$TIME_PENALTY $EXTRA_SET" \
        bash jobs/slurm_run.sh
      [[ -f "$logdir/metrics.json" || -f "$STOP_FILE" ]] && break
      mv "$OUT/$name.log" "$OUT/$name.try${attempt}.log" 2>/dev/null
      if (( attempt < MAX_ATTEMPTS )); then
        status "RETRY $name (attempt $((attempt + 1))/$MAX_ATTEMPTS, resuming from checkpoint)"
        sleep 20
      fi
    done
  done
done
# shellcheck disable=SC2086
run_step aggregate "$PY" scripts/train_cardreamer.py --comparison --aggregate-only \
  --task "$TASK" --arms $ARMS --seeds $SEEDS --obs camera_route --logdir "$RUN_DIR"
status "=== encoder comparison finished ==="
