#!/usr/bin/env bash
# Long-run queue for the laptop (one GPU, so steps run one after another):
#   1. Phase 2 JEPA, EMA regulariser       (~1.4 h, 30k steps)
#   2. Phase 2 JEPA, SIGReg regulariser    (~2.2 h, 30k steps)
#   3. Probe diagnostics for both + random init (~7 min): steering and speed,
#      global-mean / 2x2 / 4x4 pooling (scripts/probe_diagnostics.py)
#   4. Pick the larger speed-R2 gain over the random encoder (final weights)
#      -> outputs/checkpoints/phase2/best.pt (used by the custom_jepa arm)
#   5. Stage 3: resume the CNN/BEV run from its checkpoint with
#      train_ratio 512 (CarDreamer's setting) up to DREAMER_STEPS (~3 h)
#
# Every step resumes if the script is started again, and a failed step does
# not stop the later ones. Progress: outputs/long_runs/status.txt; full logs
# in outputs/long_runs/; machine health every 30 s in outputs/long_runs/health.log.
#
# Crash protection: a health monitor stops the trainers (SIGTERM, both save a
# checkpoint) and halts the queue if the GPU stays >= GPU_TEMP_LIMIT C for 90 s,
# available RAM < MIN_RAM_GB, or free disk < MIN_DISK_GB. Start detached with
# system sleep blocked:
#   mkdir -p outputs/long_runs
#   setsid nohup systemd-inhibit --what=sleep:idle:handle-lid-switch \
#     --why="training" bash jobs/long_runs.sh > outputs/long_runs/run.log 2>&1 &
# Stop cleanly: touch outputs/long_runs/STOP   (finishes nothing new, stops trainers)
# Do not edit this file while it runs: bash reads scripts incrementally.

set -uo pipefail
PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
PY="$PROJECT_ROOT/.venv/bin/python"
export PYTHONUNBUFFERED=1  # logs show progress as it happens
OUT="outputs/long_runs"
mkdir -p "$OUT"
export CARLA_ROOT="${CARLA_ROOT:-$HOME/software/CARLA_0.9.15}"
DREAMER_STEPS="${DREAMER_STEPS:-150000}"
DREAMER_LOGDIR="${DREAMER_LOGDIR:-outputs/logs/cnn_bev_seed42}"
CONFIG="configs/phase2_jepa_laptop.yaml"
GPU_TEMP_LIMIT="${GPU_TEMP_LIMIT:-92}"
MIN_RAM_GB="${MIN_RAM_GB:-2}"
MIN_DISK_GB="${MIN_DISK_GB:-5}"
STOP_FILE="$OUT/STOP"
rm -f "$STOP_FILE"

status() { echo "$(date '+%Y-%m-%d %H:%M:%S')  $*" | tee -a "$OUT/status.txt"; }

TRAINER_PATTERN='^[^ ]*python[0-9.]* [^ ]*scripts/(train_phase2_jepa|train_cardreamer|probe_phase2)\.py'

stop_trainers() {
  # SIGTERM only the main trainer processes. The pattern is anchored to a
  # Python interpreter (never a shell that merely mentions the script), and
  # children of a trainer (DataLoader workers share its command line) are
  # skipped: the trainer shuts them down itself after checkpointing.
  local pid parent
  for pid in $(pgrep -f "$TRAINER_PATTERN"); do
    parent="$(ps -o ppid= -p "$pid" | tr -d ' ')"
    if [[ -n "$parent" ]] && tr '\0\n' '  ' < "/proc/$parent/cmdline" 2>/dev/null \
        | grep -Eq "$TRAINER_PATTERN"; then
      continue
    fi
    kill -TERM "$pid" 2>/dev/null
  done
}

health_monitor() {
  local hot=0 gpu ram disk cpu
  while true; do
    gpu="$(nvidia-smi --query-gpu=temperature.gpu,memory.used,utilization.gpu,power.draw \
           --format=csv,noheader,nounits 2>/dev/null | head -1)"
    ram="$(awk '/MemAvailable/ {printf "%.1f", $2 / 1048576}' /proc/meminfo)"
    disk="$(df -BG --output=avail "$PROJECT_ROOT" | tail -1 | tr -dc 0-9)"
    cpu="$(sensors 2>/dev/null | awk '/Package id 0/ {print $4; exit}')"
    echo "$(date '+%H:%M:%S') gpu[temp,MiB,util,W]=${gpu// /} cpu=${cpu:-?} ram_avail=${ram}G disk_free=${disk}G" \
      >> "$OUT/health.log"
    if [[ "${gpu%%,*}" =~ ^[0-9]+$ ]] && (( ${gpu%%,*} >= GPU_TEMP_LIMIT )); then
      hot=$((hot + 1))
    else
      hot=0
    fi
    local reason=""
    (( hot >= 3 )) && reason="GPU at ${gpu%%,*} C for 90 s"
    awk -v r="$ram" -v m="$MIN_RAM_GB" 'BEGIN { exit !(r < m) }' && reason="RAM available ${ram} GB"
    (( disk < MIN_DISK_GB )) && reason="disk free ${disk} GB"
    if [[ -n "$reason" ]]; then
      echo "health monitor: $reason" > "$STOP_FILE"
    fi
    if [[ -f "$STOP_FILE" ]]; then
      [[ -s "$STOP_FILE" ]] || echo "manual STOP file" > "$STOP_FILE"
      status "STOP: $(cat "$STOP_FILE"); stopping trainers"
      stop_trainers
      return
    fi
    sleep 30
  done
}

run_step() {  # name, command...
  local name="$1"; shift
  if [[ -f "$STOP_FILE" ]]; then
    status "SKIP  $name (stopped: $(cat "$STOP_FILE"))"
    return
  fi
  status "START $name"
  if "$@" > "$OUT/$name.log" 2>&1; then
    status "OK    $name"
  else
    status "FAIL  $name (exit $?, see $OUT/$name.log)"
  fi
}

phase2() {  # regulariser
  local dir="outputs/checkpoints/phase2_$1" resume=()
  if [[ -f "$dir/final.pt" ]]; then
    echo "already finished: $dir/final.pt"
    return 0
  fi
  [[ -f "$dir/latest.pt" ]] && resume=(--resume)
  "$PY" scripts/train_phase2_jepa.py --config "$CONFIG" --regularizer "$1" \
    --checkpoint-dir "$dir" "${resume[@]}"
}

select_phase2() {
  # Criterion: validation R2 gain over the random-init encoder for clip speed
  # with 4x4 spatial pooling (scripts/probe_diagnostics.py). Steering is kept
  # for information only: on comma2k19 highway driving it is not linearly
  # decodable by any encoder, random included, so it cannot rank methods.
  "$PY" - <<'PY'
import json, shutil
from pathlib import Path

r = json.loads(Path("outputs/probe_results/diagnostics.json").read_text())["results"]
probe = "speed|4x4"
random = r[f"random_init|{probe}"]["r2"]
results = {}
for reg in ("ema", "sigreg"):
    key = f"phase2_{reg}/final|{probe}"
    if key in r:
        results[reg] = {"speed_r2": r[key]["r2"], "random_speed_r2": random,
                        "gain_r2": r[key]["r2"] - random,
                        "steering_r2": r[f"phase2_{reg}/final|steering|4x4"]["r2"]}
if not results:
    raise SystemExit("no diagnostics results")
winner = max(results, key=lambda k: results[k]["gain_r2"])
dest = Path("outputs/checkpoints/phase2/best.pt")
dest.parent.mkdir(parents=True, exist_ok=True)
shutil.copy2(f"outputs/checkpoints/phase2_{winner}/final.pt", dest)
summary = {"winner": winner, "criterion": "speed R2 (4x4 pooling) - random-init R2",
           "results": results}
Path("outputs/probe_results/selection.json").write_text(json.dumps(summary, indent=2))
print(json.dumps(summary, indent=2))
PY
}

status "=== long-run queue started (Dreamer target ${DREAMER_STEPS} steps) ==="
health_monitor &
MONITOR_PID=$!
trap 'kill "$MONITOR_PID" 2>/dev/null' EXIT
run_step phase2_ema phase2 ema
run_step phase2_sigreg phase2 sigreg
run_step probe_diagnostics "$PY" scripts/probe_diagnostics.py \
  outputs/checkpoints/phase2_ema/final.pt outputs/checkpoints/phase2_sigreg/final.pt
run_step select_phase2 select_phase2
run_step dreamer_resume env RUN_MODE=cnn STEPS="$DREAMER_STEPS" \
  TRAIN_ARGS="--resume --logdir $DREAMER_LOGDIR --set train_ratio=512" bash jobs/slurm_run.sh
status "=== long-run queue finished ==="
