#!/usr/bin/env bash
# Long-run queue for the laptop (one GPU, so steps run one after another):
#   1. Phase 2 JEPA, EMA regulariser       (~1.4 h, 30k steps)
#   2. Phase 2 JEPA, SIGReg regulariser    (~2.2 h, 30k steps)
#   3. Probe diagnostics for both + random init (~7 min): steering and speed,
#      global-mean / 2x2 / 4x4 pooling (scripts/probe_diagnostics.py)
#   4. Pick the larger speed-R2 gain over the random encoder (final weights)
#      -> outputs/checkpoints/phase2/best.pt (used by the custom_jepa arm)
#   5. Stage 3: resume the CNN/BEV run from its checkpoint with
#      train_ratio 512 (CarDreamer's setting) up to DREAMER_STEPS (~3 h)
#
# Every step resumes if the script is started again, and a failed step does
# not stop the later ones. Progress: outputs/long_runs/status.txt; full logs
# in outputs/long_runs/; machine health every 30 s in outputs/long_runs/health.log.
#
# Crash protection: a health monitor stops the trainers (SIGTERM, both save a
# checkpoint) and halts the queue if the GPU stays >= GPU_TEMP_LIMIT C for 90 s,
# available RAM < MIN_RAM_GB, or free disk < MIN_DISK_GB. Start detached with
# system sleep blocked:
#   mkdir -p outputs/long_runs
#   setsid nohup systemd-inhibit --what=sleep:idle:handle-lid-switch \
#     --why="training" bash jobs/long_runs.sh > outputs/long_runs/run.log 2>&1 &
# Stop cleanly: touch outputs/long_runs/STOP   (finishes nothing new, stops trainers)
# Do not edit this file while it runs: bash reads scripts incrementally.

set -uo pipefail
PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
PY="$PROJECT_ROOT/.venv/bin/python"
OUT="outputs/long_runs"
export CARLA_ROOT="${CARLA_ROOT:-$HOME/software/CARLA_0.9.15}"
DREAMER_STEPS="${DREAMER_STEPS:-150000}"
DREAMER_LOGDIR="${DREAMER_LOGDIR:-outputs/logs/cnn_bev_seed42}"
CONFIG="configs/phase2_jepa_laptop.yaml"
source "$PROJECT_ROOT/jobs/lib_queue.sh"


phase2() {  # regulariser
  local dir="outputs/checkpoints/phase2_$1" resume=()
  if [[ -f "$dir/final.pt" ]]; then
    echo "already finished: $dir/final.pt"
    return 0
  fi
  [[ -f "$dir/latest.pt" ]] && resume=(--resume)
  "$PY" scripts/train_phase2_jepa.py --config "$CONFIG" --regularizer "$1" \
    --checkpoint-dir "$dir" "${resume[@]}"
}

select_phase2() {
  # Criterion: validation R2 gain over the random-init encoder for clip speed
  # with 4x4 spatial pooling (scripts/probe_diagnostics.py). Steering is kept
  # for information only: on comma2k19 highway driving it is not linearly
  # decodable by any encoder, random included, so it cannot rank methods.
  "$PY" - <<'PY'
import json, shutil
from pathlib import Path

r = json.loads(Path("outputs/probe_results/diagnostics.json").read_text())["results"]
probe = "speed|4x4"
random = r[f"random_init|{probe}"]["r2"]
results = {}
for reg in ("ema", "sigreg"):
    key = f"phase2_{reg}/final|{probe}"
    if key in r:
        results[reg] = {"speed_r2": r[key]["r2"], "random_speed_r2": random,
                        "gain_r2": r[key]["r2"] - random,
                        "steering_r2": r[f"phase2_{reg}/final|steering|4x4"]["r2"]}
if not results:
    raise SystemExit("no diagnostics results")
winner = max(results, key=lambda k: results[k]["gain_r2"])
dest = Path("outputs/checkpoints/phase2/best.pt")
dest.parent.mkdir(parents=True, exist_ok=True)
shutil.copy2(f"outputs/checkpoints/phase2_{winner}/final.pt", dest)
summary = {"winner": winner, "criterion": "speed R2 (4x4 pooling) - random-init R2",
           "results": results}
Path("outputs/probe_results/selection.json").write_text(json.dumps(summary, indent=2))
print(json.dumps(summary, indent=2))
PY
}

start_queue "long-run queue (Dreamer target ${DREAMER_STEPS} steps)"
run_step phase2_ema phase2 ema
run_step phase2_sigreg phase2 sigreg
run_step probe_diagnostics "$PY" scripts/probe_diagnostics.py \
  outputs/checkpoints/phase2_ema/final.pt outputs/checkpoints/phase2_sigreg/final.pt
run_step select_phase2 select_phase2
run_step dreamer_resume env RUN_MODE=cnn STEPS="$DREAMER_STEPS" \
  TRAIN_ARGS="--resume --logdir $DREAMER_LOGDIR --set train_ratio=512" bash jobs/slurm_run.sh
status "=== long-run queue finished ==="
