#!/usr/bin/env bash
# Zero-shot robustness evaluation of the trained encoder-comparison agents.
#
# Every agent (arm x seed, trained on carla_right_turn_simple in clear weather)
# is evaluated, without further training, under conditions it never saw:
#   baseline  training conditions
#   night     ClearNight
#   rain      HardRainNoon
#   sunset    ClearSunset (low sun, glare)
#   traffic   carla_right_turn_hard (dense cross traffic)
# EPISODES episodes each; the first VIDEO_EPISODES are recorded as videos with
# the native front camera, the bird's-eye view inset and a driving HUD.
# Finished evaluations are skipped when the script is started again; a CARLA
# crash retries the evaluation. Finally scripts/robustness_table.py writes
# outputs/robustness/robustness.md and robustness.png.
#
# Start detached with sleep blocked:
#   mkdir -p outputs/robustness_queue
#   setsid nohup systemd-inhibit --what=sleep:idle:handle-lid-switch --why=evaluation \
#     bash jobs/robustness.sh >> outputs/robustness_queue/run.log 2>&1 &
# Watch:  python3 scripts/watch_queue.py --out outputs/robustness_queue
# Stop:   touch outputs/robustness_queue/STOP
# Do not edit this file while it runs: bash reads scripts incrementally.

set -uo pipefail
PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
PY="$PROJECT_ROOT/.venv/bin/python"
OUT="${OUT:-outputs/robustness_queue}"
export CARLA_ROOT="${CARLA_ROOT:-$HOME/software/CARLA_0.9.15}"
RUNS="${RUNS:-outputs/comparison/carla_right_turn_simple_camera_route}"
RESULTS="${RESULTS:-outputs/robustness}"
ARMS="${ARMS:-cnn custom_jepa vjepa2}"
SEEDS="${SEEDS:-42 123}"
CONDITIONS="${CONDITIONS:-baseline night rain sunset traffic}"
EPISODES="${EPISODES:-10}"
VIDEO_EPISODES="${VIDEO_EPISODES:-1}"
MAX_ATTEMPTS="${MAX_ATTEMPTS:-3}"

source "$PROJECT_ROOT/jobs/lib_queue.sh"

condition_args() {  # condition -> "task|extra env overrides"
  case "$1" in
    baseline) echo "carla_right_turn_simple|" ;;
    night)    echo "carla_right_turn_simple|--env-set world.weather=ClearNight" ;;
    rain)     echo "carla_right_turn_simple|--env-set world.weather=HardRainNoon" ;;
    sunset)   echo "carla_right_turn_simple|--env-set world.weather=ClearSunset" ;;
    traffic)  echo "carla_right_turn_hard|" ;;
    *) return 1 ;;
  esac
}

# Step list for scripts/watch_queue.py (minutes per evaluation, roughly).
"$PY" - "$OUT/steps.json" "$ARMS" "$SEEDS" "$CONDITIONS" <<'PY'
import json, sys
path, arms, seeds, conditions = sys.argv[1:]
minutes = {"vjepa2": 6, "custom_jepa": 4, "cnn": 4}
steps = [{"name": f"{a}_s{s}_{c}", "hours": minutes.get(a, 5) / 60}
         for a in arms.split() for s in seeds.split() for c in conditions.split()]
steps.append({"name": "table", "hours": 0.01})
json.dump(steps, open(path, "w"), indent=1)
PY

start_queue "robustness evaluation (${ARMS}; seeds ${SEEDS}; ${CONDITIONS})"
for arm in $ARMS; do
  for seed in $SEEDS; do
    ckpt="$RUNS/${arm}_seed${seed}/latest.pt"
    if [[ ! -f "$ckpt" ]]; then
      status "SKIP  ${arm}_s${seed} (no checkpoint $ckpt)"
      continue
    fi
    for cond in $CONDITIONS; do
      name="${arm}_s${seed}_${cond}"
      dest="$RESULTS/${arm}_seed${seed}/${cond}"
      if [[ -f "$dest/evaluation_metrics.json" ]]; then
        status "DONE  $name"
        continue
      fi
      IFS='|' read -r task extra <<< "$(condition_args "$cond")"
      for attempt in $(seq 1 "$MAX_ATTEMPTS"); do
        run_step "$name" env RUN_MODE=evaluate CHECKPOINT="$ckpt" ARM="$arm" TASK="$task" \
          EPISODES="$EPISODES" OUTPUT_DIR="$dest" \
          CARLA_LOG="$PROJECT_ROOT/$OUT/carla_${name}_try${attempt}.log" \
          EVAL_ARGS="$extra --video-episodes $VIDEO_EPISODES" \
          bash jobs/slurm_run.sh
        [[ -f "$dest/evaluation_metrics.json" || -f "$STOP_FILE" ]] && break
        status "RETRY $name (attempt $((attempt + 1))/$MAX_ATTEMPTS)"
        sleep 10
      done
    done
  done
done
run_step table "$PY" scripts/robustness_table.py --results "$RESULTS"
status "=== robustness evaluation finished ==="
