#!/usr/bin/env bash
# Stage 3 retry: fresh CNN / bird's-eye-view run on carla_right_turn_simple with
# a small per-step time penalty (CarDreamer reward.scales.time, default 0), at
# train_ratio 512. Without it the agent learned to stop mid-turn and wait out
# the time limit, because standing still was free (journal 2026-10-03).
#
# Same protection as jobs/long_runs.sh (jobs/lib_queue.sh): health monitor,
# STOP file, checkpoints every 2,500 env steps and on stop; rerun to resume.
# Start detached with sleep blocked:
#   mkdir -p outputs/stage3_time_penalty
#   setsid nohup systemd-inhibit --what=sleep:idle:handle-lid-switch --why=training \
#     bash jobs/stage3_time_penalty.sh >> outputs/stage3_time_penalty/run.log 2>&1 &
# Watch:  python3 scripts/watch_run.py outputs/logs/cnn_bev_tp01_seed42 --target 150000
# Stop:   touch outputs/stage3_time_penalty/STOP
# Do not edit this file while it runs: bash reads scripts incrementally.

set -uo pipefail
PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
PY="$PROJECT_ROOT/.venv/bin/python"
OUT="outputs/stage3_time_penalty"
export CARLA_ROOT="${CARLA_ROOT:-$HOME/software/CARLA_0.9.15}"
STEPS="${STEPS:-150000}"
LOGDIR="${LOGDIR:-outputs/logs/cnn_bev_tp01_seed42}"
TIME_PENALTY="${TIME_PENALTY:-0.1}"

source "$PROJECT_ROOT/jobs/lib_queue.sh"

start_queue "stage 3 time-penalty run (${STEPS} steps, time penalty ${TIME_PENALTY})"
RESUME=""
[[ -f "$LOGDIR/latest.pt" ]] && RESUME="--resume"
run_step dreamer env RUN_MODE=cnn STEPS="$STEPS" \
  TRAIN_ARGS="$RESUME --logdir $LOGDIR --set train_ratio=512 --env-set reward.scales.time=$TIME_PENALTY" \
  bash jobs/slurm_run.sh
status "=== stage 3 time-penalty run finished ==="
